//! 前端构建产物（web/dist）→ 编译期内嵌资源表生成器。
//!
//! 默认 feature `embed-static-web` 开启：与原先一致，dist 编入二进制。
//! 关闭该 feature（`dev.sh` 使用）时仅生成空资源表，运行时通过环境变量
//! `PERI_STUDIO_WEB_DIST` 从磁盘提供静态文件，前端改动无需重编 Rust。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn embed_static_web_enabled() -> bool {
    env::var("CARGO_FEATURE_EMBED_STATIC_WEB").is_ok()
}

fn write_empty_assets(out_dir: &Path) {
    let code = "// @generated by server/build.rs — embed-static-web disabled.\n\
pub(crate) struct Asset {\n    pub url: &'static str,\n    pub bytes: &'static [u8],\n}\n\
pub(crate) static ASSETS: &[Asset] = &[];\n";
    fs::write(out_dir.join("assets.rs"), code).expect("write empty assets.rs");
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    if !embed_static_web_enabled() {
        println!(
            "cargo:warning=peri-studio-server built without embed-static-web; \
             set PERI_STUDIO_WEB_DIST to a web/dist directory at runtime."
        );
        write_empty_assets(&out_dir);
        return;
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dist = manifest_dir.join("../web/dist");
    println!("cargo:rerun-if-changed={}", dist.display());

    if !dist.join("index.html").is_file() {
        eprintln!(
            "\n错误：前端构建产物缺失（{}）。\n\
             cargo build 需要 web/dist 就绪，请先构建前端：\n\
             \n\
                 cd web && bun install && bun run build\n\
             \n\
             dev.sh 会自动检测并构建；CI 流水线也需先执行前端构建。\n",
            dist.display()
        );
        std::process::exit(1);
    }

    let assets_dir = out_dir.join("web-assets");
    fs::create_dir_all(&assets_dir).expect("create web-assets");

    let mut files: Vec<String> = Vec::new();
    collect_files(&dist, &dist, &mut files);
    files.sort();
    for rel in &files {
        println!("cargo:rerun-if-changed={}", dist.join(rel).display());
    }

    for rel in &files {
        let src = dist.join(rel);
        let dst = assets_dir.join(rel);
        if let Some(parent) = dst.parent() {
            fs::create_dir_all(parent).expect("create asset subdir");
        }
        fs::copy(&src, &dst).expect("copy asset");
    }

    let mut code = String::new();
    code.push_str("// @generated by server/build.rs —— 由 web/dist 构建产物生成，勿手改。\n");
    code.push_str(
        "pub(crate) struct Asset {\n    pub url: &'static str,\n    pub bytes: &'static [u8],\n}\n",
    );
    code.push_str("pub(crate) static ASSETS: &[Asset] = &[\n");
    for rel in &files {
        code.push_str(&format!(
            "    Asset {{ url: {:?}, bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/web-assets/{}\")) }},\n",
            rel, rel
        ));
    }
    code.push_str("];\n");
    fs::write(out_dir.join("assets.rs"), code).expect("write assets.rs");
}

fn collect_files(base: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, out);
        } else {
            let rel = path.strip_prefix(base).expect("strip prefix");
            out.push(rel.to_string_lossy().into_owned());
        }
    }
}
