//! 前端构建产物（web/dist）→ 编译期内嵌资源表生成器。
//!
//! peri-studio 前端是独立 Vite 工程（web/，SolidJS，唯一生产入口 `/`；
//! `/panel.html` 只是兼容路由），构建产物 dist/ 不提交 git。本脚本在
//! 编译期扫描 dist/：把全部文件复制进 OUT_DIR 并生成 assets.rs
//! （Asset 表，字节经 include_bytes! 引用，零运行时文件 IO、零新依赖），
//! server/src/web/mod.rs 以 include!(concat!(env!("OUT_DIR"), "/assets.rs"))
//! 引入。产物文件名带内容 hash，路由按实际文件清单生成，无需约定固定名。
//!
//! dist 缺失 → 编译失败并提示构建命令（与 include_str! 语义一致：cargo
//! build 成功 ⇒ web 一定可用；dev.sh 会先自动检测并构建前端）。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dist = manifest_dir.join("../web/dist");
    // 目录级监视在部分 Cargo/filesystem 组合下不会可靠感知 Vite 的
    // 内容 hash 文件替换；同时为每个实际产物声明监视，避免 server 继续
    // 内嵌上一版 bundle。
    println!("cargo:rerun-if-changed={}", dist.display());

    if !dist.join("index.html").is_file() {
        eprintln!(
            "\n错误：前端构建产物缺失（{}）。\n\
             cargo build 需要 web/dist 就绪，请先构建前端：\n\
             \n\
                 cd web && bun install && bun run build\n\
             \n\
             dev.sh 会自动检测并构建；CI 流水线也需先执行前端构建。\n",
            dist.display()
        );
        std::process::exit(1);
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let assets_dir = out_dir.join("web-assets");
    fs::create_dir_all(&assets_dir).expect("create web-assets");

    // 递归收集相对路径并排序（构建确定性：assets.rs 内容稳定）。
    let mut files: Vec<String> = Vec::new();
    collect_files(&dist, &dist, &mut files);
    files.sort();
    for rel in &files {
        println!("cargo:rerun-if-changed={}", dist.join(rel).display());
    }

    for rel in &files {
        let src = dist.join(rel);
        let dst = assets_dir.join(rel);
        if let Some(parent) = dst.parent() {
            fs::create_dir_all(parent).expect("create asset subdir");
        }
        fs::copy(&src, &dst).expect("copy asset");
    }

    let mut code = String::new();
    code.push_str("// @generated by server/build.rs —— 由 web/dist 构建产物生成，勿手改。\n");
    code.push_str(
        "pub(crate) struct Asset {\n    pub url: &'static str,\n    pub bytes: &'static [u8],\n}\n",
    );
    code.push_str("pub(crate) static ASSETS: &[Asset] = &[\n");
    for rel in &files {
        code.push_str(&format!(
            "    Asset {{ url: {:?}, bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/web-assets/{}\")) }},\n",
            rel, rel
        ));
    }
    code.push_str("];\n");
    fs::write(out_dir.join("assets.rs"), code).expect("write assets.rs");
}

fn collect_files(base: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, out);
        } else {
            let rel = path.strip_prefix(base).expect("strip prefix");
            out.push(rel.to_string_lossy().into_owned());
        }
    }
}
